# Generated by Django 4.0.6 on 2022-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='surat_masuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_surat', models.CharField(max_length=100)),
                ('tanggal_terima', models.DateField()),
                ('nomor_surat', models.IntegerField()),
                ('pengirim', models.CharField(max_length=100)),
                ('perihal', models.CharField(max_length=100)),
                ('ditunjukan', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
